version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    env_file: ./.env
    container_name: $DB_CONTAINER_NAME
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./tbl_devices.sql:/docker-entrypoint-initdb.d/table_devices.sql
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    expose:
      - $DB_LOCAL_PORT
    networks:
      - backend

  api:
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - backend
      - frontend

  ui:
    depends_on:
      - api
    build:
      context: ./ui
      dockerfile: ../docker/ui/Dockerfile
    env_file: ./ui/.env
    environment:
        - REACT_APP_API_URL=$REACT_APP_API_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  postgres:

networks:
  backend:
  frontend: